### ISSUE TITLE
Add homepage to affiliation information for author

### ISSUE THREAD

**Issue by dressedfez** [dressedfez/myst_template_physical_review_journals#1]
Currently this is not yet supported by myst. The state of the implementation can be found here: https://github.com/executablebooks/mystjs/issues/321

**Comment by stevejpurves** [comment]
this is now addressed? https://github.com/dressedfez/myst_template_physical_review_journals/blob/3aeb50d988556d6fc5fa098645b3b65fa676e42b/template.tex#L90

**Comment by dressedfez** [comment]
> this is now addressed?
> 
> https://github.com/dressedfez/myst_template_physical_review_journals/blob/3aeb50d988556d6fc5fa098645b3b65fa676e42b/template.tex#L90

Since this works here, as far as I can remember, I would say yes.

I guess we could add this to the[ documentation](https://myst-tools.org/docs/mystjs/frontmatter#authors).

**Comment by stevejpurves** [comment]
👍🏼 https://github.com/executablebooks/mystjs/pull/424
