### ISSUE TITLE
Provide example article that uses all options introduced in this template

### ISSUE THREAD

**Issue by dressedfez** [dressedfez/myst_template_physical_review_journals#2]

**Comment by dressedfez** [comment]
@rowanc1 can we use your [article](https://library.seg.org/doi/10.1190/tle35080703.1) here or would it be better that I will provide one of my publications?

**Comment by rowanc1** [comment]
Feel free to use that article if it works for this template! It has a `cc-by-sa-3.0` license on the article (notebooks + content are cc-by/MIT).

The myst version is here:
https://github.com/simpeg/tle-finitevolume

**Comment by dressedfez** [comment]
This should be enough for the beginning.
